### ISSUE TITLE
payload and DevTools

### ISSUE THREAD

**Issue by mailok** [amcdnl/ngxs#109]
hi! I've noticed that in the DevTools not shown to payload of action.
this is my acction:
```
export class AddTodo {
  static type = '[Foo] Some';
  constructor(public readonly payload: string) {}
}
```
```
@Action(AddTodo)
  addTodo({ getState, setState }: StateContext<string[]>, { payload }: AddTodo) {
    setState([...getState(), payload]);
  }
```
```
this.store.dispatch(new AddTodo(todo));

```

and this pictured is dispached action with payload

![captura](https://user-images.githubusercontent.com/3769277/37673311-41f6ea6c-2c46-11e8-90c2-cc1b068de023.PNG)

As you can see, the payload is not displayed

**Comment by amcdnl** [comment]
Fixed. It was sending previous state.

**Comment by mailok** [comment]
hi!, sorry, but i test 2.0.0-rc.18 and still does not show the payload in action
